### ISSUE TITLE
Segfault in InitCl () at main.cpp:262

### ISSUE THREAD

**Issue by inferrna** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#25]
All 58 tests with ../Bin/Debug/x64/UnitTest64D passed but
```
(gdb) run -p ../Resources/bmw/ -f ../Resources/bmw/i8.obj
Starting program: /media/Compressed/Drivers_bios/src/dev/FireRays_SDK/Bin/Debug/x64/App64D -p ../Resources/bmw/ -f ../Resources/bmw/i8.obj
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdb7e5700 (LWP 2400)]
[New Thread 0x7fffd5efc700 (LWP 2401)]

Thread 1 "App64D" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffce56209f in ?? () from /usr/lib/libamdocl64.so
#2  0x00007fffce458944 in ?? () from /usr/lib/libamdocl64.so
#3  0x00007fffce458a59 in ?? () from /usr/lib/libamdocl64.so
#4  0x00007fffce46438b in ?? () from /usr/lib/libamdocl64.so
#5  0x00007fffce42984e in clCreateContext () from /usr/lib/libamdocl64.so
#6  0x0000000000433e38 in CLWContext::Create (devices=std::vector of length 1, capacity 1 = {...}, props=props@entry=0x7fffffffd5d0) at CLWContext.cpp:40
#7  0x0000000000433fc1 in CLWContext::Create (device=..., props=props@entry=0x7fffffffd5d0) at CLWContext.cpp:193
#8  0x000000000040743e in ConfigManager::CreateConfigs (mode=ConfigManager::kUseSingleGpu, interop=true, configs=std::vector of length 0, capacity 0)
    at config_manager.cpp:108
#9  0x0000000000419ba3 in InitCl () at main.cpp:262
#10 0x0000000000406a5e in main (argc=5, argv=0x7fffffffd978) at main.cpp:808
(gdb) quit
```
[clinfo.txt](https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK/files/267731/clinfo.txt)

**Comment by yozhijk** [comment]
Did you try disabling GL interop with --interop 0 flag?

**Comment by inferrna** [comment]
Works with ```-interop 0``` thank you
```
../Bin/Debug/x64/App64D -p ../Resources/bmw/ -f i8.obj -interop 0
Running on devices: 
0: Pitcairn
OpenGL interop mode disabled
Loading complete
Number of objects: 152
Number of textures: 0
Number of emissives: 0
Commited in 2.616s
Vidmem usage (data): 50Mb
Polygon count 559196
Vidmem usage (working set): 114Mb
1 OpenCL submission threads started
```
